inherit_from:
  - .rubocop_enabled.yml
  - .rubocop_disabled.yml

AllCops:
  Include:
    - '**/*.rb'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/config.ru'
    - 'config/initializers/*'
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/application.rb'
    - 'config/environments/*'
    - 'db/**/*'
    - 'Capfile'
    - 'config/deploy/*'
    - 'config/deploy.rb'
  NewCops: enable
