name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  rubocop:
    name: Run Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          bundler-cache: true
      - name: Run security checks
        run: |
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2
      - name: Run rubocop
        run: bundle exec rubocop --parallel
